### Test h5.model prediction

In [17]:
from keras.models import load_model
from keras.utils import np_utils
class_num =20

In [5]:
path = '/home/zxt/data/128/5k_size/'

In [3]:
model = load_model('/home/zxt/data/128/model/model_vgg_200epoch_32batch_2k_128.h5')

In [6]:
import  numpy as np
X_test = np.load(path+'X_test_128.npy')
Y_test = np.load(path+'Y_test_128.npy')

In [7]:
predict = model.predict(X_test)

In [8]:
predict

array([[2.4214180e-02, 6.8267420e-02, 2.7509673e-02, ..., 2.2726551e-02,
        5.8826722e-02, 6.9114514e-02],
       [2.7490454e-02, 4.4411920e-02, 8.3980158e-02, ..., 7.6266848e-02,
        8.1003852e-02, 2.4114465e-02],
       [1.0897921e-08, 8.0207522e-17, 2.5726437e-13, ..., 6.8780531e-07,
        6.8425757e-06, 4.3019067e-16],
       ...,
       [7.1038154e-04, 1.8567118e-01, 1.9268431e-04, ..., 4.9829356e-02,
        1.9494091e-07, 5.5817649e-02],
       [5.2524194e-02, 4.9123827e-02, 5.1768217e-02, ..., 5.1291440e-02,
        5.2986607e-02, 4.9019806e-02],
       [3.2535598e-02, 4.9764894e-02, 3.8627606e-02, ..., 6.2951341e-02,
        6.0362262e-03, 1.0858396e-01]], dtype=float32)

In [8]:
len(predict)

9000

In [9]:
len(Y_test)

9000

In [10]:
Y_test[:5]

array([['fox'],
       ['black_bear'],
       ['cattle'],
       ['cattle'],
       ['fox']], dtype='<U16')

In [15]:
predict[:5]

array([[2.42141802e-02, 6.82674199e-02, 2.75096726e-02, 4.42745052e-02,
        4.19245176e-02, 4.29995656e-02, 8.86883214e-02, 5.41208573e-02,
        7.12266192e-02, 3.42463627e-02, 6.52256384e-02, 2.84163859e-02,
        9.97349527e-03, 9.02075768e-02, 5.29141352e-02, 7.99621418e-02,
        2.51607168e-02, 2.27265507e-02, 5.88267222e-02, 6.91145137e-02],
       [2.74904538e-02, 4.44119200e-02, 8.39801580e-02, 2.24148966e-02,
        3.34977657e-02, 8.51244256e-02, 3.93065289e-02, 3.12454738e-02,
        2.95881350e-02, 2.00510826e-02, 6.08657412e-02, 7.70855248e-02,
        1.66875366e-02, 6.61816671e-02, 7.84482509e-02, 4.81810272e-02,
        5.40542565e-02, 7.62668476e-02, 8.10038522e-02, 2.41144653e-02],
       [1.08979208e-08, 8.02075218e-17, 2.57264370e-13, 8.82384238e-16,
        9.99979138e-01, 3.45930119e-14, 1.01807676e-16, 5.93320999e-15,
        5.34487344e-06, 4.01313628e-06, 8.16003928e-15, 1.24997411e-13,
        7.59976970e-08, 8.75933909e-11, 4.00555863e-13, 3.6189

In [11]:
for i in Y_test:
    if i[0]=='elephant':
        i[0]=0
    if i[0]=='wild_boar':
        i[0]=1
    if i[0]=='gazellethomosons':
        i[0]=2
    if i[0]=='squirrel':
        i[0]=3 
    if i[0]=='hedgehog':
        i[0]=4
    if i[0]=='guineafowl':
        i[0]=5
    if i[0]=='moose':
        i[0]=6
    if i[0]=='bobcat':
        i[0]=7   
    if i[0]=='bird':
        i[0]=8
    if i[0]=='fox':
        i[0]=9
    if i[0]=='giraffe':
        i[0]=10
    if i[0]=='buffalo':
        i[0]=11
    if i[0]=='hare':
        i[0]=12
    if i[0]=='vehicle':
        i[0]=13
    if i[0]=='wildebeest':
        i[0]=14
    if i[0]=='cattle':
        i[0]=15 
    if i[0]=='skunk':
        i[0]=16
    if i[0]=='lion':
        i[0]=17
    if i[0]=='zebra':
        i[0]=18
    if i[0]=='black_bear':
        i[0]=19

In [12]:
Y_test

array([['9'],
       ['19'],
       ['15'],
       ...,
       ['2'],
       ['18'],
       ['0']], dtype='<U16')

In [13]:
print(np.unique(Y_test))

['0' '1' '10' '11' '12' '13' '14' '15' '16' '17' '18' '19' '2' '3' '4' '5'
 '6' '7' '8' '9']


In [18]:
Y_test_1 = np_utils.to_categorical(Y_test, class_num)

In [20]:
Y_test_1[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.], dtype=float32)

In [21]:
Y_test[0]

array(['9'], dtype='<U16')

In [24]:
loss,accuracy = model.evaluate(X_test,Y_test_1)
print('\ntest loss',loss)
print('accuracy',accuracy)

9000/9000 [==============================] - 27s 3ms/step

test loss 0.9050455861091614
accuracy 0.8583333492279053
